eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-turbine
server:
  port: 8767
turbine:
  aggregator:
    cluster-config: default
  app-config: ribbon,eureka-feign-client
  cluster-name-expression: new String("default")
  instanceUrlSuffix: /hystrix.stream